-- +goose Up
CREATE TABLE fx_SGD (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_EUR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_JPY (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_SDR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_VND (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_TWD (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_THB (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_SAR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_PKR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_PHP (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_NZD (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_NPR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_MMK (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_KRW (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_KHR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_INR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_IDR (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_HKD (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_GBP (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_EGP (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_CNY (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_CHF (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_CAD (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_BND (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_AUD (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_AED (
    id UUID PRIMARY KEY,
    exchange_rate DECIMAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS fx_SGD;
DROP TABLE IF EXISTS fx_EUR;
DROP TABLE IF EXISTS fx_JPY;
DROP TABLE IF EXISTS fx_SDR;
DROP TABLE IF EXISTS fx_VND;
DROP TABLE IF EXISTS fx_TWD;
DROP TABLE IF EXISTS fx_THB;
DROP TABLE IF EXISTS fx_SAR;
DROP TABLE IF EXISTS fx_PKR;
DROP TABLE IF EXISTS fx_PHP;
DROP TABLE IF EXISTS fx_NZD;
DROP TABLE IF EXISTS fx_NPR;
DROP TABLE IF EXISTS fx_MMK;
DROP TABLE IF EXISTS fx_KRW;
DROP TABLE IF EXISTS fx_KHR;
DROP TABLE IF EXISTS fx_INR;
DROP TABLE IF EXISTS fx_IDR;
DROP TABLE IF EXISTS fx_HKD;
DROP TABLE IF EXISTS fx_GBP;
DROP TABLE IF EXISTS fx_EGP;
DROP TABLE IF EXISTS fx_CNY;
DROP TABLE IF EXISTS fx_CHF;
DROP TABLE IF EXISTS fx_CAD;
DROP TABLE IF EXISTS fx_BND;
DROP TABLE IF EXISTS fx_AUD;
DROP TABLE IF EXISTS fx_AED;

